# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_realloc/Makefile -- build obj_realloc unit test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_realloc
OBJS = obj_realloc.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
