# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_pmalloc_basic/Makefile -- build obj_pmalloc_basic unit test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_pmalloc_basic
OBJS = obj_pmalloc_basic.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
