# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_alloc/Makefile -- build obj_alloc unit test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_alloc
OBJS = obj_alloc.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
