# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP
#

#
# src/test/obj_defrag/Makefile -- build obj_defrag unit test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_defrag
OBJS = obj_defrag.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
