# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_reserve_mt/Makefile -- build obj_reserve_mt unit test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_reserve_mt
OBJS = obj_reserve_mt.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
