# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_memops/Makefile -- build obj_memops test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_memops
OBJS = obj_memops.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
