#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/util_sds_check/TEST1 -- unittest for shutdown shutdown_state_check
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type any

require_build_type debug

setup

expect_normal_exit ./util_sds_check test_case_2

check

pass
