# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_many_size_allocs/Makefile -- build obj_many_size_allocs test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_many_size_allocs
OBJS = obj_many_size_allocs.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
