# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2019, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_tx_flow/Makefile -- build obj_tx_flow unit test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_tx_flow
OBJS = obj_tx_flow.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
