# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026, Hewlett Packard Enterprise Development LP

#
# src/test/obj_ctl_stats_curr_allocated_wa/Makefile --
#
TARGET = obj_ctl_stats_curr_allocated_wa
OBJS = obj_ctl_stats_curr_allocated_wa.o

BUILD_STATIC_DEBUG=n
BUILD_STATIC_NONDEBUG=n

LIBPMEMOBJ=y

include ../Makefile.inc
