# Run all tests on PMEM.
#
# This workflow is run on 'self-hosted' runners.
name: PMEM tests part 2

on:
  workflow_dispatch:
  schedule:
    # run this job at 18:00 UTC every other day (odd-numbered)
    - cron:  '0 18 */2 * *'

permissions: {}

jobs:
  # Test the default build with force-enabled Valgrind tooling for (persistent)
  # memory error detection.
  Memory:
    uses: ./.github/workflows/pmem_test_matrix.yml
    with:
      force_enable: '["pmemcheck", "memcheck"]'
      valgrind: 1
      # 12h = 720m (arbitrarily picked in hope it will be enough).
      timeout_minutes: 720


  # Test the default build with force-enabled Valgrind tooling for thread error
  # detection.
  Thread:
    uses: ./.github/workflows/pmem_test_matrix.yml
    with:
      force_enable: '["drd", "helgrind"]'
      valgrind: 1
      # 12h = 720m (arbitrarily picked in hope it will be enough).
      timeout_minutes: 720
