# Run all tests on PMEM.
#
# This workflow is run on 'self-hosted' runners.
name: PMEM tests part 2

on:
  workflow_dispatch:
  schedule:
    # run this job at 6:00 UTC every Saturday
    - cron:  '0 6 * * 6'

permissions: {}

jobs:
  # Test the default build with force-enabled Valgrind tooling for (persistent)
  # memory error detection.
  Memory:
    uses: ./.github/workflows/pmem_test_matrix.yml
    with:
      force_enable: '["pmemcheck", "memcheck"]'
      valgrind: 1
      # 24h = 1440m (arbitrarily picked in hope it will be enough).
      timeout_minutes: 1440
