# Run all tests w/o valgrind on PMEM.
#
# This workflow is run on 'self-hosted' runners.
name: PMEM tests w/o valgrind

on:
  workflow_dispatch:
  schedule:
    # run this job at 18:00 UTC every day
    - cron:  '0 18 * * *'

permissions: {}

jobs:
  # Test the default build with the basic test suite.
  Basic:
    name: Basic w/o Valgrind
    uses: ./.github/workflows/pmem_test_matrix.yml
    with:
      force_enable: '["none"]'
      valgrind: 0


  # By default, PMDK is built with NDCTL in order to provide RAS features.
  # This build is only viable as long as DAOS builds PMDK with NDCTL_ENABLE=n
  # https://github.com/daos-stack/pmdk/pull/12
  # It should be removed as soon as following PR is merged
  # https://github.com/daos-stack/pmdk/pull/35
  ndctl_enable_n:
    name: Without ndctl
    if: github.repository_owner == 'daos-stack'
    runs-on: [self-hosted, pmdk, rhel]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Test prepare
        uses: ./.github/actions/pmem_test_prepare
        with:
          ndctl_enable: n
          valgrind: 0

      - name: Test run
        uses: ./.github/actions/pmem_test_run
        with:
          build: nondebug # only the production build is considered
