# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2018-2024, Intel Corporation
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_pmemcheck/Makefile -- build obj_pmemcheck unit test
#
TOP = ../../..
vpath % .c $(TOP)/src/common/

TARGET = obj_pmemcheck
OBJS = obj_pmemcheck.o shutdown_state_helper.o

LIBPMEMOBJ=internal-debug

include ../Makefile.inc
